### ISSUE TITLE
Default Movement Controls

### ISSUE THREAD

**Issue by reeve567** [Hugobros3/chunkstories#12]
I'm not sure if it's something to do with my setup, but upon loading into a world for the first time the only usable movement controls were `S` and `D`.

Upon going into the controls and setting forward and left to `W` and `A` respectively, I could move normally.

Not sure if you're aware of this, but the controls for jump and run display `null` in the controls menu but still work with space and shift

*Will try to look through source to see if I can find anything, though probably not*

**Comment by Hugobros3** [comment]
Yeah this is kind of messy, the default controls were at some point automatically decided based on the locale you chose (to match french Azerty keyboards), but with the move to LWJGL3 this is no longer useful (since it ignores layout), and the autoselect feature appears broken as well. Fixing this is very easy though, you can simply modify `default.inputs` in `chunkstories-core`, I'll let you make a PR or change it myself, whatever suits you best.

Regarding the controls displaying as null, it's a minor glitch I should address at some point as well, not as trivial but probably easy.

**Comment by reeve567** [comment]
I'll see what I can do tonight, I forgot about the build instructions when I was originally looking for it earlier today

**Comment by reeve567** [comment]
Should be done, PR at https://github.com/Hugobros3/chunkstories-core/pull/5

Figured I should close this as this was in the wrong repo, and there's comments on the PR
